#!/usr/bin/env python3
"""CUDA-only MeloTTS Japanese JSON-lines worker."""

from __future__ import annotations

import hashlib
import os
import sys
import types
from typing import Any, Mapping

from _autoanki_tts_worker_common import (
    MELO_BACKEND,
    MELO_MODEL_ID,
    RequestError,
    clean_batch_outputs_on_error,
    cuda_inventory,
    gpu_synthesis_lease,
    installed_path,
    leased_cuda_inventory,
    load_installation,
    revision_for_assets,
    run_worker,
    seed_synthesis,
    status_response,
    success_artifact,
    validate_synthesis_request,
    validate_synthesis_items,
    write_tensor_wav,
)


VOICE_ID = "JP"
TOKENIZER_ID = "tohoku-nlp/bert-base-japanese-v3"
SOURCE_REVISION = "209145371cff8fc3bd60d7be902ea69cbdb7965a"


def _source_tree_fingerprint(directory) -> str:
    """Hash stable source files while ignoring generated bytecode caches."""
    if not directory.is_dir():
        raise RequestError(
            f"Pinned MeloTTS source package is missing: {directory}")
    digest = hashlib.sha256()
    entry_count = 0
    for path in sorted(
            directory.rglob("*"),
            key=lambda candidate: candidate.relative_to(directory).as_posix()):
        relative = path.relative_to(directory)
        if (
                "__pycache__" in relative.parts
                or path.suffix in {".pyc", ".pyo"}):
            continue
        if path.is_symlink():
            kind = b"L"
            content_digest = hashlib.sha256(
                os.readlink(path).encode("utf-8")).digest()
        elif path.is_file():
            kind = b"F"
            file_digest = hashlib.sha256()
            with path.open("rb") as stream:
                while block := stream.read(1024 * 1024):
                    file_digest.update(block)
            content_digest = file_digest.digest()
        else:
            continue
        name = relative.as_posix().encode("utf-8")
        digest.update(kind)
        digest.update(len(name).to_bytes(8, "big"))
        digest.update(name)
        digest.update(content_digest)
        entry_count += 1
    if not entry_count:
        raise RequestError(
            f"Pinned MeloTTS source package contains no files: {directory}")
    return digest.hexdigest()


def _installation_and_voice() -> tuple[dict, dict[str, str]]:
    installation = load_installation(MELO_BACKEND, MELO_MODEL_ID)
    voice_metadata = installation.get("voice")
    if (
            not isinstance(voice_metadata, dict)
            or voice_metadata.get("id") != VOICE_ID):
        raise RequestError("The installed MeloTTS voice is not JP.")
    source = installed_path(installation, "source", regular_file=False)
    config = installed_path(
        installation, "model_config", regular_file=True)
    checkpoint = installed_path(
        installation, "model_checkpoint", regular_file=True)
    tokenizer = installed_path(
        installation, "tokenizer", regular_file=False)
    tokenizer_config = tokenizer / "tokenizer_config.json"
    tokenizer_vocab = tokenizer / "vocab.txt"
    if not tokenizer_config.is_file() or not tokenizer_vocab.is_file():
        raise RequestError("The pinned MeloTTS Japanese tokenizer is incomplete.")
    source_metadata = installation.get("source")
    if not isinstance(source_metadata, dict):
        raise RequestError("The pinned MeloTTS source metadata is missing.")
    source_revision = source_metadata.get("revision")
    if source_revision != SOURCE_REVISION:
        raise RequestError("The pinned MeloTTS source revision is incorrect.")
    expected_tree_revision = source_metadata.get("tree_sha256")
    if (
            not isinstance(expected_tree_revision, str)
            or len(expected_tree_revision) != 64
            or any(
                character not in "0123456789abcdef"
                for character in expected_tree_revision)):
        raise RequestError(
            "The pinned MeloTTS source-tree revision is missing.")
    actual_tree_revision = _source_tree_fingerprint(source / "melo")
    if actual_tree_revision != expected_tree_revision:
        raise RequestError(
            "The pinned MeloTTS source tree was modified after installation.")
    revision = revision_for_assets((
        ("model-config", config),
        ("model-checkpoint", checkpoint),
        ("tokenizer-config", tokenizer_config),
        ("tokenizer-vocabulary", tokenizer_vocab),
    ), text_assets=(
        ("source-revision", source_revision),
        ("source-tree-sha256", actual_tree_revision),
        ("speaker", VOICE_ID),
    ))
    return installation, {VOICE_ID: revision}


def _status() -> dict:
    model_revision = None
    voices: dict[str, str] = {}
    installation_ok = False
    try:
        installation, voices = _installation_and_voice()
        model_revision = installation["model"]["revision"]
        installation_ok = True
    except Exception:
        pass
    gpu_available, device_name, _problem = leased_cuda_inventory(MELO_BACKEND)
    return status_response(
        backend=MELO_BACKEND,
        model_id=MELO_MODEL_ID,
        model_revision=model_revision,
        runtime_available=installation_ok,
        gpu_available=gpu_available,
        device_name=device_name,
        voices=voices if installation_ok else {})


def _validate_melo_item(data: Mapping[str, Any]) -> None:
    if data["pitch"] != 0.0:
        raise RequestError(
            "The installed MeloTTS path does not implement pitch "
            "adjustment; use 0.0.")


def _speaker_id(model) -> int:
    speaker_ids = getattr(model.hps.data, "spk2id", None)
    try:
        speaker_id = speaker_ids[VOICE_ID]
    except (AttributeError, KeyError, TypeError) as error:
        raise RequestError(
            "MeloTTS did not expose its JP speaker ID.") from error
    if isinstance(speaker_id, bool) or not isinstance(speaker_id, int):
        raise RequestError("MeloTTS exposed an invalid JP speaker ID.")
    return speaker_id


def _load_model(installation: Mapping[str, Any]):
    gpu_available, _device_name, problem = cuda_inventory()
    if not gpu_available:
        raise RequestError(problem or "CUDA is unavailable.")

    source = installed_path(installation, "source", regular_file=False)
    tokenizer_path = installed_path(
        installation, "tokenizer", regular_file=False)
    sys.path.insert(0, str(source))
    # Normal generation is deliberately offline. Melo's Japanese frontend
    # hardcodes this tokenizer ID, so redirect that exact request to the
    # immutable installed tokenizer rather than following Hugging Face main.
    os.environ["HF_HUB_OFFLINE"] = "1"
    os.environ["TRANSFORMERS_OFFLINE"] = "1"
    from transformers import AutoTokenizer

    original_from_pretrained = AutoTokenizer.from_pretrained

    def pinned_from_pretrained(identifier, *args, **kwargs):
        if identifier != TOKENIZER_ID:
            raise RequestError(
                f"MeloTTS attempted to load an unpinned tokenizer: "
                f"{identifier!r}")
        return original_from_pretrained(
            str(tokenizer_path), local_files_only=True)

    AutoTokenizer.from_pretrained = staticmethod(pinned_from_pretrained)

    # Upstream's cleaner eagerly imports every language frontend. This
    # Japanese-only runtime supplies the same cleaner contract while loading
    # only the selected Japanese frontend and its pinned tokenizer.
    from melo.text import japanese

    cleaner = types.ModuleType("melo.text.cleaner")

    def clean_text(text, language):
        if language != VOICE_ID:
            raise RequestError(
                f"The MeloTTS Japanese runtime cannot clean {language!r}.")
        normalized = japanese.text_normalize(text)
        phones, tones, word_to_phone = japanese.g2p(normalized)
        return normalized, phones, tones, word_to_phone

    cleaner.clean_text = clean_text
    sys.modules["melo.text.cleaner"] = cleaner

    from melo.api import TTS

    model = TTS(
        language=VOICE_ID,
        device="cuda:0",
        use_hf=False,
        config_path=str(installed_path(
            installation, "model_config", regular_file=True)),
        ckpt_path=str(installed_path(
            installation, "model_checkpoint", regular_file=True)))
    try:
        parameter = next(model.model.parameters())
    except (AttributeError, StopIteration) as error:
        raise RequestError(
            "MeloTTS did not expose its synthesis model.") from error
    if parameter.device.type != "cuda":
        raise RequestError("MeloTTS did not load its model on CUDA.")
    return model, _speaker_id(model)


def _synthesize_item(model, speaker_id: int, data: Mapping[str, Any]) -> dict:
    import torch

    seed_synthesis(data["seed"])
    audio = model.tts_to_file(
        data["text"],
        speaker_id,
        output_path=None,
        speed=data["speed"],
        quiet=True)
    torch.cuda.synchronize()
    write_tensor_wav(
        audio,
        int(model.hps.data.sampling_rate),
        data["sample_rate_hz"],
        data["output_path"])
    return success_artifact(data)


def _synthesize(request: Mapping[str, Any]) -> dict:
    installation, voices = _installation_and_voice()
    data = validate_synthesis_request(
        request,
        installation,
        supported_languages={"japanese"},
        voice_revisions=voices)
    _validate_melo_item(data)
    with gpu_synthesis_lease(MELO_BACKEND):
        model, speaker_id = _load_model(installation)
        return _synthesize_item(model, speaker_id, data)


def _synthesize_many(request: Mapping[str, Any]) -> dict:
    installation, voices = _installation_and_voice()
    items = validate_synthesis_items(
        request,
        installation,
        supported_languages={"japanese"},
        voice_revisions=voices)
    for item in items:
        _validate_melo_item(item)
    with clean_batch_outputs_on_error(items):
        with gpu_synthesis_lease(MELO_BACKEND):
            model, speaker_id = _load_model(installation)
            artifacts = [
                _synthesize_item(model, speaker_id, item)["artifact"]
                for item in items
            ]
    return {"artifacts": artifacts}


def handle(
        request: Mapping[str, Any],
        operation: str) -> Mapping[str, Any]:
    if operation == "status":
        return _status()
    if operation == "synthesize_many":
        return _synthesize_many(request)
    return _synthesize(request)


if __name__ == "__main__":
    sys.exit(run_worker(
        backend=MELO_BACKEND,
        model_id=MELO_MODEL_ID,
        handler=handle))
