"""Resumable, offline-testable generation from processed source corpora.

This package deliberately does not construct an OpenAI client or talk to Anki.
The caller must inject the paid request operation and, later, explicitly import
the resulting deck.  That boundary keeps planning and cost estimation free.
"""

from source_generation.adapters import SourceGenerationBackend
from source_generation.jobs import (
    GenerationJobRunner,
    GenerationJobStore,
    JobEvent,
    JobSnapshot,
    PaidDispatchControl,
    PaidDispatchPaused,
    PaidResponse,
    RetryPolicy,
    is_transient_request_error,
)
from source_generation.models import (
    AnkiExclusionSpec,
    ContextOccurrenceSpan,
    ContextMode,
    ContextUnit,
    CostEstimate,
    GenerationChunk,
    GenerationPlan,
    GenerationWord,
    LoadedSource,
    OutputDetail,
    Pricing,
    SourceGenerationConfig,
)
from source_generation.planning import (
    AUD_EXCHANGE_RATE_LABEL,
    BATCH_PRICING,
    DEFAULT_PRICING,
    LOW_REASONING_OUTPUT_RESERVE_MULTIPLIER,
    MODEL_CONTEXT_WINDOW_TOKENS,
    MODEL_MAX_INPUT_TOKENS,
    MODEL_MAX_OUTPUT_TOKENS,
    STANDARD_PRICING,
    USD_TO_AUD_RATE,
    estimate_plan_cost,
    estimate_chunk_output_tokens,
    estimate_text_tokens,
    list_processed_source_summaries,
    list_processed_sources,
    load_processed_source,
    plan_source_generation,
    price_source_usage,
    resolve_latest_processed_source_path,
)
from source_generation.validation import (
    inspect_pipeline_response,
    make_pipeline_response_validator,
    public_validation_report,
)
from source_generation.requests import (
    SOURCE_BATCH_INSTRUCTIONS,
    SOURCE_REQUEST_CONTRACT_SCHEMA_VERSION,
    SOURCE_REQUEST_MODEL,
    SOURCE_REQUEST_REASONING,
    build_source_request_contract,
    build_source_prompt,
    compact_response_format_uses_occurrence_sense_indices,
    load_source_batch_instructions,
    load_source_web_search_instructions,
    normalise_source_request_contract,
    render_chunk_input,
    source_request_contract_digest,
    source_request_includes_context_nuance,
    source_request_requires_generated_examples,
    source_request_requires_sentence_translations,
    source_request_uses_compact_source_results,
    source_request_uses_grouped_source_results,
    source_request_uses_obsolete_context_translation_protocol,
    source_request_uses_occurrence_locators,
    source_request_uses_sentence_arrays,
    source_request_uses_split_contextual_cards,
)

__all__ = (
    "AnkiExclusionSpec",
    "ContextOccurrenceSpan",
    "ContextMode",
    "ContextUnit",
    "CostEstimate",
    "AUD_EXCHANGE_RATE_LABEL",
    "BATCH_PRICING",
    "DEFAULT_PRICING",
    "MODEL_CONTEXT_WINDOW_TOKENS",
    "MODEL_MAX_INPUT_TOKENS",
    "MODEL_MAX_OUTPUT_TOKENS",
    "STANDARD_PRICING",
    "USD_TO_AUD_RATE",
    "GenerationChunk",
    "GenerationJobRunner",
    "GenerationJobStore",
    "GenerationPlan",
    "GenerationWord",
    "JobEvent",
    "JobSnapshot",
    "LoadedSource",
    "LOW_REASONING_OUTPUT_RESERVE_MULTIPLIER",
    "OutputDetail",
    "PaidDispatchControl",
    "PaidDispatchPaused",
    "PaidResponse",
    "Pricing",
    "RetryPolicy",
    "SourceGenerationConfig",
    "SourceGenerationBackend",
    "SOURCE_BATCH_INSTRUCTIONS",
    "SOURCE_REQUEST_CONTRACT_SCHEMA_VERSION",
    "SOURCE_REQUEST_MODEL",
    "SOURCE_REQUEST_REASONING",
    "build_source_request_contract",
    "build_source_prompt",
    "compact_response_format_uses_occurrence_sense_indices",
    "load_source_batch_instructions",
    "load_source_web_search_instructions",
    "normalise_source_request_contract",
    "estimate_plan_cost",
    "estimate_chunk_output_tokens",
    "estimate_text_tokens",
    "is_transient_request_error",
    "inspect_pipeline_response",
    "list_processed_source_summaries",
    "list_processed_sources",
    "load_processed_source",
    "make_pipeline_response_validator",
    "plan_source_generation",
    "price_source_usage",
    "resolve_latest_processed_source_path",
    "render_chunk_input",
    "public_validation_report",
    "source_request_contract_digest",
    "source_request_includes_context_nuance",
    "source_request_requires_generated_examples",
    "source_request_requires_sentence_translations",
    "source_request_uses_compact_source_results",
    "source_request_uses_grouped_source_results",
    "source_request_uses_obsolete_context_translation_protocol",
    "source_request_uses_occurrence_locators",
    "source_request_uses_sentence_arrays",
    "source_request_uses_split_contextual_cards",
)
